---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: lbc
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: 8s.gcr.io/echoserver:1.10
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - name: http
          containerPort: 8080
          
