---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: hpa
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: k8s.gcr.io/echoserver:1.10
          ports:
            - name: http
              containerPort: 8080
          resources:  # its mandatory for using hpa 
            requests:
              memory: 256Mi
              cpu: 100m
            limits:
              memory: 256Mi
              cpu: 100m